POST http://127.0.0.1:5000/recipe/ HTTP/1.1
content-type: application/json

{
  "description": "Test description",
  "imageFile": null,
  "isFavorite": false,
  "note": "",
  "recipeId": 66,
  "title": "Test recipe 12",
  "urlRoute": "test-recipe-12"
}
