POST http://127.0.0.1:5000/recipe/ HTTP/1.1
content-type: application/json

{
  "description": "Test description",
  "imageFile": null,
  "isFavorite": false,
  "note": "",
  "title": "Test recipe 12",
  "route": "test-recipe-12",
  "modifiedDate": "2023-11-04 06:46:07"
}
